### ISSUE TITLE
Change the spacing and styling of the error components 

### ISSUE THREAD

**Issue by shaunajisc** [JiscSD/octopus#107]
The styling of the `error` component styling is inconsistent with the rest of the Octopus site. Need to change the: 
- font 
- spacing 
- icon 
- placeholder text 

![image](https://user-images.githubusercontent.com/100135505/161062460-04f2335d-e152-4d48-a31d-9f476161e10d.png)

**Comment by AshleyRedmanJisc** [comment]
It would be good if we followed something similar to whats provided here: https://tailwindui.com/components/application-ui/feedback/alerts
