### ISSUE TITLE
Publication page is not reactive.

### ISSUE THREAD

**Issue by AshleyRedmanJisc** [JiscSD/octopus#149]
This page does not revalidate upon mutation. It seems a temp fix for this was introduced in the bookmark feature to pre load state with prop data from SSR. This causes issues with client side routing. Local state needs removing & the pre fetched data from SSR needs to be passed to useSWR as the initial state / fallback then inform SWR when mutation occur to have a fully reactive page.

**Comment by reubenporterjisc** [comment]
#166
