### ISSUE TITLE
Overlapping linked publication title text

### ISSUE THREAD

**Issue by lharre** [JiscSD/octopus#85]
On individual publication pages, in the linked publications section, the spacing of title text can overlap when the title runs to multiple lines. 

The issue only seems to apply where a publication title runs to multiple lines: https://int.octopus.ac/publications/publication-user-4-data-1-live. 
![Spacing for linked text](https://user-images.githubusercontent.com/97461921/157052746-7dccb3b0-0632-43b3-b2f6-016e94ff793d.png)

This is not an issue for publications which have multiple linked publications: https://int.octopus.ac/publications/publication-user-2-data-1-live

**Comment by nathan-at-jisc** [comment]
Resolved in the latest release.
