### ISSUE TITLE
Publication process - update dummy text to content 

### ISSUE THREAD

**Issue by lharre** [JiscSD/octopus#86]
Current publication process pages are populated with placeholder text. 

General notes 
No footer visible during publication process
Save - add text making it clear that the user has to manually save before leaving. Later we ideally we want a save as well as a save and exit option. 
At the moment I can't save and exit until I've submitted conflict of interest reason, even if I haven't looked at this page yet. 

Page 1  
Add publication types to drop down (like that used for license information).  
Remove icons.  
Add note: Please note that the publication type cannot be changed after this stage.   

Right hand side: 
Publication title 
Titles should be concise, specific, and informative – this will help relevant readers find your material. 

Publication types: 
Octopus has 8 publication types which align with the scientific process.   

Page 2  
What is the title of this publication? change to > Publication title  

Typos in publication type explanation. Amend to: 
You have selected the publication type xxx.  
Please note that this cannot be changed.  If you wish to change publication type, you must delete this publication and create a new one. 

Page 3 - links 
Ignoring for now! Needs reworking.  
For future: Problem can’t be linked from peer review.  

Page 4 – license, COI 
License 
Shift dropdown to always open
Add 4.0 to the end of each option.  
Add link to this page: https://creativecommons.org/licenses/ 

Conflict of interest 
This needs to be an active statement that the publication 'does NOT have a conflict of interest' 
 
If preference is not to show text box unless required, have options: 
Does this publication have any conflicts of interest? 
[] This publication does not have any conflicts of interest 
[] There are conflicting interests to declare (opens text box) 

 Page 5 – review  
Update copy: 
Coming soon...  
This will be a page to review all content before publishing. 
It is not possible to make any changes post-publication.

**Comment by lharre** [comment]
@nathan-at-jisc I think this is now covered by the changes made last week.

**Comment by AshleyRedmanJisc** [comment]
@lharre & @nathan-at-jisc I think this issue is good to close?

**Comment by AshleyRedmanJisc** [comment]
The majority of the points here have been covered apart from the first (footer), so when a PR covers that ill close this issue.

**Comment by AshleyRedmanJisc** [comment]
@lharre All of the above should be in place now, aside from the footer being in the publication process. I think we purposely left this out as it results in the below: 
![Screenshot 2022-04-27 at 12 45 45](https://user-images.githubusercontent.com/81176162/165511482-97b3a2f1-ece4-481b-866b-898f7973709d.png)

If you're ok with us leaving the footer off this, then I can close this issue?
